### ISSUE TITLE
Feature request: syntax highlighting/formatting for RumorScript 

### ISSUE THREAD

**Issue by dhowe** [exodrifter/unity-rumor#48]
Would be great to get minimal syntax highlighting (and possibly even auto-format) for RumorScript in popular editors (I'm using Visual Studio Code)

**Comment by exodrifter** [comment]
Thanks for your feedback! That sounds like an excellent idea. I did this once for sublime, but I've forgotten how to do it since and I've lost the file.

I can take a look into doing this when I come back from the holidays.

Would sublime and vscode cover what you use? Let me know if there is another editor you'd like support for.

**Comment by dhowe** [comment]
Great. I use Atom (generally) rather than Sublime as its FOSS, and then VSCode when working in Unity...

Here's some info: https://code.visualstudio.com/docs/extensionAPI/language-support#_syntax-highlighting

**Comment by exodrifter** [comment]
Alright! I'll be closing this ticket and making new tickets for Sublime, Atom, and VSCode. Anyone who comes across this later, feel free to open a new ticket requesting support for another editor.
