### ISSUE TITLE
Feature request: full Unity example project

### ISSUE THREAD

**Issue by dhowe** [exodrifter/unity-rumor#49]
I have one running now, but it took me a while to setup a Unity project for the example -- would be great (for new users) to be able to just open a Unity project and press 'play' to see Rumor in action...

**Comment by exodrifter** [comment]
I would love to have an example scene ready to go as well - except there are a few problems with that idea.

The repository doesn't keep track of `.meta` files because they aren't required to make the code work. This is mostly because I don't want to add unnecessary files to C#  projects that don't use Unity. However, Unity requires the .meta files in order to know what items have been added to a Unity scene asset.

You should be able to run the example by creating a Text asset and attaching the Example script by dragging it into the GameObject in the Hierarchy. I thought that wouldn't be too troublesome for Unity users, but you make a good point (along with your other bug reports). It makes it hard to tell if you did something wrong while setting the project up or if it was actually just my fault.

I'll include an Example scene in .unitypackage releases from now on. This means I'll start tracking `.meta` files. At the very least, it shouldn't be too hard for other C# projects to either ignore or delete the `.meta` files. If someone requires it, I can also create a C#-specific repository, but since my main target audience is Unity users, I won't do that for now. Maybe I'll find a better solution in the future that will let me avoid making a C#-specific repository since it would be a pain to keep them in sync.

**Comment by exodrifter** [comment]
This feature was added in [1.1.1](https://github.com/exodrifter/unity-rumor/releases/tag/1.1.1).
